// DKY Jewelry product catalog.
window.DKY_PRODUCTS = [
  {
    id: "curb-chain-necklace",
    name: "Curb Chain Necklace",
    category: "Necklaces",
    karat: 18,
    weightGrams: 22,
    priceType: "fixed",
    priceUsd: 2450,
    priceMinUsd: 2450,
    priceMaxUsd: 2450,
    image: "assets/products/chain-necklace.jpg",
    shortDesc: "Bold 18k curb chain, polished finish.",
    description:
      "A statement curb chain in solid 18k gold. Substantial weight, smooth links, and a secure lobster clasp. Designed to wear daily and pass down.",
    details: [
      "Solid 18k yellow gold",
      "Length: 50 cm",
      "Width: 6 mm",
      "Lobster clasp closure",
      "Hallmarked & certified",
    ],
  },
  {
    id: "wedding-band",
    name: "Classic Wedding Band",
    category: "Rings",
    karat: 18,
    weightGrams: 6,
    priceType: "fixed",
    priceUsd: 720,
    priceMinUsd: 720,
    priceMaxUsd: 720,
    image: "assets/products/wedding-band.jpg",
    shortDesc: "Timeless 18k band, brushed finish.",
    description:
      "A modern take on the classic wedding band. Brushed exterior, polished interior for comfort. Available in multiple sizes.",
    details: [
      "Solid 18k yellow gold",
      "Width: 4 mm",
      "Comfort-fit interior",
      "Brushed satin finish",
      "Sizes 5–13 available",
    ],
  },
  {
    id: "hoop-earrings",
    name: "Polished Hoop Earrings",
    category: "Earrings",
    karat: 14,
    weightGrams: 4.5,
    priceType: "range",
    priceMinUsd: 385,
    priceMinUsd: 350,
    priceMaxUsd: 420,
    image: "assets/products/hoop-earrings.jpg",
    shortDesc: "Lightweight 14k hoops with click closure.",
    description:
      "Everyday hoops with a high-shine finish. Lightweight enough for daily wear, with a secure click-back closure.",
    details: [
      "Solid 14k yellow gold",
      "Diameter: 25 mm",
      "Tube width: 2 mm",
      "Hinged click-back",
      "Hypoallergenic",
    ],
  },
  {
    id: "tennis-bracelet",
    name: "Diamond Tennis Bracelet",
    category: "Bracelets",
    karat: 18,
    weightGrams: 12,
    priceType: "fixed",
    priceUsd: 3850,
    priceMinUsd: 3850,
    priceMaxUsd: 3850,
    image: "assets/products/tennis-bracelet.jpg",
    shortDesc: "18k bracelet set with brilliant-cut diamonds.",
    description:
      "A continuous line of brilliant-cut diamonds set in 18k yellow gold. Double safety clasp for peace of mind.",
    details: [
      "Solid 18k yellow gold",
      "2.5 ct total diamond weight",
      "Length: 18 cm",
      "Double safety clasp",
      "Conflict-free diamonds",
    ],
  },
  {
    id: "signet-ring",
    name: "Engraved Signet Ring",
    category: "Rings",
    karat: 22,
    weightGrams: 14,
    priceType: "hidden",     // Precio no mostrado, consultar vía WhatsApp
    image: "assets/products/signet-ring.jpg",
    shortDesc: "Heavy 22k signet, custom engraving available.",
    description:
      "A heavy, traditional signet ring in 22k gold. Engrave your initials, family crest, or a meaningful symbol.",
    details: [
      "Solid 22k yellow gold",
      "Face: 16 × 13 mm oval",
      "Custom engraving on request",
      "Hand-finished",
      "Sizes 6–14 available",
    ],
  },
  {
    id: "signet-ring",
    name: "Engraved Signet Ring",
    category: "Rings",
    karat: 22,
    weightGrams: 14,
    priceType: "hidden",     // Precio no mostrado, consultar vía WhatsApp
    image: "assets/products/signet-ring.jpg",
    shortDesc: "Heavy 22k signet, custom engraving available.",
    description:
      "A heavy, traditional signet ring in 22k gold. Engrave your initials, family crest, or a meaningful symbol.",
    details: [
      "Solid 22k yellow gold",
      "Face: 16 × 13 mm oval",
      "Custom engraving on request",
      "Hand-finished",
      "Sizes 6–14 available",
    ],
  },
  {
    id: "solitaire-pendant",
    name: "Solitaire Pendant",
    category: "Necklaces",
    karat: 18,
    weightGrams: 3.2,
    priceType: "fixed",
    priceUsd: 920,
    priceMinUsd: 920,
    priceMaxUsd: 920,
    image: "assets/products/pendant.jpg",
    shortDesc: "Single stone pendant on a fine 18k chain.",
    description:
      "A delicate solitaire pendant on a fine cable chain. Bezel-set stone for a smooth, modern silhouette.",
    details: [
      "Solid 18k yellow gold",
      "Chain length: 45 cm (adjustable)",
      "Bezel-set 0.25 ct stone",
      "Spring-ring clasp",
      "Gift box included",
    ],
  },
];